---
# tasks file for apache2
- name: Install python-apt
  ansible.builtin.apt:
    name: python-apt
    state: latest

- name: Install apache2
  ansible.builtin.apt:
    name: apache2
    state: latest

- name: Copy apache2.conf
  ansible.builtin.copy:
    src: '{{ config }}'
    dest: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: '0644'
- name: Copy index.html
  ansible.builtin.copy:
    src: '{{ index }}'
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
- name: Create symbolic link
  ansible.builtin.file:
    src: /etc/apache2/mods-available/headers.load
    dest: /etc/apache2/mods-enabled/headers.load
    owner: root
    group: root
    state: link
  notify: Restart apache2
